const productEnum = {
  condition: ['New', 'Recondition', 'Used'],
  steering: ['Left', 'Right'],
  fuelType: ['Diesel', 'Petrol', 'CNG', 'Hybrid', 'Octane', 'LPG', 'Other'],
  transmission: ['Automatic', 'Semi Automatic', 'Manual', 'CVT', 'DCT', 'SportAT', 'Other'],
  bodyType: [
    'MPV',
    'Hypercar',
    'Supercar',
    'Electric',
    'Convertible',
    'Coupe',
    'Pickup',
    'Mini MPV',
    'Vagon',
    'Off Roader',
    'Van',
    'Mini Van',
    'Hatchback',
    'Crossover',
    'SUV',
    'Sedan',
  ],
  color: [
    'Gray',
    'Black',
    'White',
    'Pink',
    'Gold',
    'Blue',
    'Red',
    'Silver',
    'Brown',
    'Lime Green',
    'Purple',
    'Orange',
    'Beige',
    'Yellow',
    'Dark Green',
    'Green',
    'Mica Blue',
    'Sky Blue',
    'Dark Blue',
    'Navy Blue',
    'Red Wine',
    // 'Pearl',
  ],
  drivetrain: ['2 Wheel Drive', '4 Wheel Drive'],
  features: [
    { label: 'CD Player', value: 'cdPlayer' },
    { label: 'Sun Roof', value: 'sunRoof' },
    { label: 'Alloy Wheels', value: 'alloyWheels' },
    { label: 'Power Steering', value: 'powerSteering' },
    { label: 'Power Window', value: 'powerWindow' },
    { label: 'AC', value: 'ac' },
    { label: 'Abs', value: 'abs' },
    { label: 'Air Bag', value: 'airBag' },
    { label: 'CD Changer', value: 'cdChanger' },
    { label: 'Radio', value: 'radio' },
    { label: 'DVD', value: 'dvd' },
    { label: 'TV', value: 'tv' },
    { label: 'Power Seat', value: 'powerSeat' },
    { label: 'Back Tire', value: 'backTire' },
    { label: 'Grill Guard', value: 'grillGuard' },
    { label: 'Rear Spoiler', value: 'rearSpoiler' },
    { label: 'Center Locking', value: 'centerLocking' },
    { label: 'Jack', value: 'jack' },
    { label: 'Spare Tire', value: 'spareTire' },
    { label: 'Wheel Spanner', value: 'wheelSpanner' },
    { label: 'Fog Light', value: 'fogLight' },
    { label: 'Back Camera', value: 'backCamera' },
    { label: 'Push Start', value: 'pushStart' },
    { label: 'Key Lessentry', value: 'keyLessentry' },
    { label: 'ESC', value: 'esc' },
    { label: '360D Camera', value: '360DCamera' },
    { label: 'Body Kit', value: 'bodyKit' },
    { label: 'Side Airbag', value: 'sideAirbag' },
    { label: 'Power Mirror', value: 'powerMirror' },
    { label: 'Side Skirts', value: 'sideSkirts' },
    { label: 'Font LipSpoiler', value: 'fontLipSpoiler' },
    { label: 'Navigation', value: 'navigation' },
    { label: 'Turbo', value: 'turbo' },
    { label: 'Non Smoker', value: 'nonSmoker' },
  ],
  numberOfSeat: [1, 2, 3, 4, 5, 6, 7, 8],
}

export default productEnum
