const productEnum = {
  condition: ['New', 'Recondition', 'Used'],
  steering: ['Left', 'Right'],
  fuelType: ['Diesel', 'Petrol', 'CNG', 'Hybrid', 'Octane', 'LPG', 'Other'],
  transmission: ['Automatic', 'SemiAutomatic', 'Manual', 'CVT', 'DCT', 'SportAT', 'Other'],
  bodyType: [
    'MPV',
    'Hypercar',
    'Supercar',
    'Electric',
    'Convertible',
    'Coupe',
    'Pickup',
    'Mini MPV',
    'Vagon',
    'Off Roader',
    'Van',
    'Mini Van',
    'Hatchback',
    'Crossover',
    'SUV',
    'Sedan',
  ],
  color: [
    'Gray',
    'Black',
    'White',
    'Pink',
    'Gold',
    'Blue',
    'Red',
    'Silver',
    'Brown',
    'Lime Green',
    'Purple',
    'Orange',
    'Beige',
    'Yellow',
    'Dark Green',
    'Green',
    'Mica Blue',
    'Sky Blue',
    'Dark Blue',
    'Navy Blue',
    'Red Wine',
    'Pearl',
  ],
  drivetrain: ['2Wheel Drive', '4Wheel Drive'],
}

export default productEnum
