const productEnum = {
  condition: ['New', 'Recondition', 'Used'],
  steering: ['Left', 'Right'],
  fuelType: ['Diesel', 'Petrol', 'CNG', 'Hybrid', 'Octane', 'LPG', 'Other'],
  transmission: ['Automatic', 'Semi Automatic', 'Manual', 'CVT', 'DCT', 'SportAT', 'Other'],
  bodyType: [
    'MPV',
    'Hypercar',
    'Supercar',
    'Electric',
    'Convertible',
    'Coupe',
    'Pickup',
    'Mini MPV',
    'Vagon',
    'Off Roader',
    'Van',
    'Mini Van',
    'Hatchback',
    'Crossover',
    'SUV',
    'Sedan',
  ],
  color: [
    'Gray',
    'Black',
    'White',
    'Pink',
    'Gold',
    'Blue',
    'Red',
    'Silver',
    'Brown',
    'Lime Green',
    'Purple',
    'Orange',
    'Beige',
    'Yellow',
    'Dark Green',
    'Green',
    'Mica Blue',
    'Sky Blue',
    'Dark Blue',
    'Navy Blue',
    'Red Wine',
    'Pearl',
  ],
  drivetrain: ['2 Wheel Drive', '4 Wheel Drive'],
  features: [
    'cdPlayer',
    'sunRoof',
    'alloyWheels',
    'powerSteering',
    'powerWindow',
    'ac',
    'abs',
    'airBag',
    'cdChanger',
    'radio',
    'dvd',
    'tv',
    'powerSeat',
    'backTire',
    'grillGuard',
    'rearSpoiler',
    'centerLocking',
    'jack',
    'spareTire',
    'wheelSpanner',
    'fogLight',
    'backCamera',
    'pushStart',
    'keyLessentry',
    'esc',
    '360DCamera',
    'bodyKit',
    'sideAirbag',
    'powerMirror',
    'sideSkirts',
    'fontLipSpoiler',
    'navigation',
    'turbo',
    'nonSmoker',
  ],
}

export default productEnum
