export enum BodyTypeEnum {
  MPV = 'MPV',
  Hypercar = 'Hypercar',
  Supercar = 'Supercar',
  Electric = 'Electric',
  Convertible = 'Convertible',
  Coupe = 'Coupe',
  Pickup = 'Pickup',
  MiniMPV = 'Mini MPV',
  Vagon = 'Vagon',
  OffRoader = 'Off Roader',
  Van = 'Van',
  MiniVan = 'Mini Van',
  Hatchback = 'Hatchback',
  Crossover = 'Crossover',
  SUV = 'SUV',
  Sedan = 'Sedan',
}
