export enum ColorEnum {
  Gray = 'Gray',
  Black = 'Black',
  White = 'White',
  Pink = 'Pink',
  Gold = 'Gold',
  Blue = 'Blue',
  Red = 'Red',
  Silver = 'Silver',
  Brown = 'Brown',
  LimeGreen = 'Lime Green',
  Purple = 'Purple',
  Beige = 'Beige',
  Yellow = 'Yellow',
  Orange = 'Orange',
  DarkGreen = 'Dark Green',
  Green = 'Green',
  SkyBlue = 'Sky Blue',
  MicaBlue = 'Mica Blue',
  DarkBlue = 'Dark Blue',
  NavyBlue = 'Navy Blue',
  RedWine = 'Red Wine',
  Pearl = 'Pearl',
}
