### Get list of all feedbacks
GET http://localhost:3900/api/v1/feedbacks

### Get a single feedback by id
GET http://localhost:3900/api/v1/feedbacks/dc090666-8f60-4399-ad09-33754a606f96

### Create a feedback
POST  http://localhost:3900/api/v1/feedbacks
Content-Type: application/json

{
  "description": "description"
}

### Update a feedback by id
PUT   http://localhost:3900/api/v1/feedbacks/101641e2-bd11-4e49-83d9-72895fa511ef
Content-Type: application/json

{
  "description": "description"
}

### Delete a feedback by id
DELETE   http://localhost:3900/api/v1/feedbacks/28bac04b-0150-4cc0-a49e-823abb9dae77
