### Get All brands
GET http://localhost:3900/api/v1/brands

### GET a single brand
GET http://localhost:3900/api/v1/brands/a0e592d0-7a8f-40d8-96f3-7a690da1fe73

### Create a brand
POST http://localhost:3900/api/v1/brands
Content-Type: application/json

{
   "name":"Brand A"
}

### Update a brand
PUT http://localhost:3900/api/v1/brands/a0e592d0-7a8f-40d8-96f3-7a690da1fe73
Content-Type: application/json

{
    "name":"Brand B"
    
}

### Delete a brand
DELETE http://localhost:3900/api/v1/brands/a0e592d0-7a8f-40d8-96f3-7a690da1fe73